#!/usr/bin/env bash
# One-time project setup.
#
# This repo holds only the Dart source; the android/ platform scaffolding is
# generated by `flutter create` rather than committed, so it matches whatever
# Flutter version you actually have. Run this once after cloning.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

if ! command -v flutter >/dev/null 2>&1; then
  echo "ERROR: flutter is not on your PATH."
  echo "Install it from https://docs.flutter.dev/get-started/install/macos"
  exit 1
fi

echo "==> Flutter version"
flutter --version

# flutter create can overwrite files it thinks it owns, so the hand-written
# sources are set aside and restored around it.
STASH="$(mktemp -d)"
echo "==> Stashing sources to $STASH"
for item in lib test pubspec.yaml analysis_options.yaml; do
  [ -e "$item" ] && cp -R "$item" "$STASH/"
done

echo "==> Generating platform scaffolding"
flutter create \
  --platforms=android \
  --org com.caffeinatedcompilers \
  --project-name khatasetu \
  . >/dev/null

echo "==> Restoring sources"
for item in lib test pubspec.yaml analysis_options.yaml; do
  [ -e "$STASH/$item" ] && rm -rf "$ROOT/$item" && cp -R "$STASH/$item" "$ROOT/"
done
rm -rf "$STASH"

echo "==> Applying Android configuration"
python3 scripts/configure_android.py

echo "==> Fetching packages"
flutter pub get

echo
echo "Setup complete."
echo "  flutter test      # run the logic tests"
echo "  flutter run       # build to a connected device"
echo
echo "The on-device LLM and speech models are OFF by default."
echo "See docs/NATIVE_AI.md and docs/MODELS.md to turn them on."
